apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-logger-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: shared-hostpath
  hostPath:
    path: /mnt/shared-logs
