apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-logger-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: shared-hostpath

