apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-proxy.fullname" . }}
  labels:
    app: {{ include "llm-proxy.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    app: {{ include "llm-proxy.name" . }}
