apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "logger.fullname" . }}
  labels:
    app: {{ include "logger.name" . }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
