apiVersion: argoproj.io/v1alpha1
######
kind: ApplicationSet
metadata:
  name: llm-platform-microservices
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/abdel124/ai_threat_defense.git
        revision: main
        directories:
          - path: helm/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/abdel124/ai_threat_defense.git
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: llm-platform
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
